project/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path


from books import views as books_views
from base import views as base_views

from django.conf import settings


urlpatterns = [
    path('', base_views.home, name='home'),
    path('', base_views.home, name='library/archive'),
    path('library/<str:library_slug>/', books_views.library_single, name='library/single'),
    
    path('libraries/edit/<str:library_id>/categories/edit/<str:category_id>/books/edit/<str:book_id>/', books_views.edit_book, name='library-category-book/edit'),
    path('libraries/edit/<str:library_id>/categories/edit/<str:category_id>/books/add/', books_views.edit_book, name='library-category-book/add'),
    path('libraries/edit/<str:library_id>/categories/edit/<str:category_id>/books/', books_views.book_archive, name='library-category-book/archive'),
    
    path('libraries/edit/<str:library_id>/categories/edit/<str:category_id>/', books_views.edit_category, name='library-category/edit'),
    path('libraries/edit/<str:library_id>/categories/add/', books_views.edit_category, name='library-category/add'),
    path('libraries/edit/<str:library_id>/categories/', books_views.archive_category, name='library-category/archive'),

    path('libraries/edit/<str:library_id>/', books_views.edit_library, name='library/edit'),
    path('libraries/add/', books_views.edit_library, name='library/add'),
    
    path('admin/', admin.site.urls),
    path('logout/', base_views.user_logout, name='logout'),
    path('profile/', base_views.user_profile, name='profile'),

    url(r'^oauth/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.contrib.auth.models import User
from django.db import models


from project.utils import md5ify_model, slugify_model


class LibraryTemplate(models.Model):
	name = models.CharField(max_length=100, default='')
	slug = models.CharField(max_length=100, blank=True, default='')

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		if not self.slug.strip():
			self.slug = slugify_model(self.__class__, self.__str__())
		super().save(args, kwargs)


class Library(models.Model):
	name = models.CharField(max_length=200, default='')
	slug = models.CharField(max_length=8, blank=True, default='')
	template = models.ForeignKey(LibraryTemplate, blank=True, null=True, on_delete=models.PROTECT)
	user = models.ForeignKey(User, blank=True, null=True, on_delete=models.PROTECT)
	active = models.BooleanField(default=False)

	def __str__(self):
		return self.name + " - " + self.user.username

	def save(self, *args, **kwargs):
		if not self.slug.strip():
			self.slug = md5ify_model(self.__class__)
		super().save(args, kwargs)


class LibraryCategory(models.Model):
	name = models.CharField(max_length=200, default='')
	library = models.ForeignKey(Library, blank=True, null=True, on_delete=models.PROTECT)
	active = models.BooleanField(default=False)
	order = models.IntegerField(default=0, null=True)

	class Meta:
		ordering = ('order', )

	def __str__(self):
		return self.name# + " - " + self.library.name

	def save(self, *args, **kwargs):
		if self.order == 0:
			 category = LibraryCategory.objects.filter(library=self.library).order_by("-order").first()
			 if category is not None:
			 	self.order = category.order + 1
			 else:
			 	self.order = 1
		super().save(args, kwargs)


class Book(models.Model):
	name = models.CharField(max_length=200, default='')
	url = models.CharField(max_length=300, default='')
	category = models.ForeignKey(LibraryCategory, blank=True, null=True, on_delete=models.PROTECT)
	cover = models.ImageField(null=True)
	order = models.IntegerField(default=0, null=True)

	class Meta:
		ordering = ('order', )

	def save(self, *args, **kwargs):
		if self.order == 0:
			 book = Book.objects.filter(category=self.category).order_by("-order").first()
			 if book is not None:
			 	self.order = book.order + 1
			 else:
			 	self.order = 1
		super().save(args, kwargs)

base/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from social_django.models import UserSocialAuth

from books.models import Library


@login_required
def user_logout(request):
	logout(request)
	return redirect('home')


@login_required
def user_profile(request):
	user = request.user

	try:
		github_login = user.social_auth.get(provider='github')
	except UserSocialAuth.DoesNotExist:
		github_login = None

	try:
		google_login = user.social_auth.get(provider='google-oauth2')
	except UserSocialAuth.DoesNotExist:
		google_login = None

	try:
		facebook_login = user.social_auth.get(provider='facebook')
	except UserSocialAuth.DoesNotExist:
		facebook_login = None

	can_disconnect = (user.social_auth.count() > 1)

	return render(request, 'base/profile.html', {
		'github_login': github_login,
		'google_login': google_login,
		'facebook_login': facebook_login,
		'can_disconnect': can_disconnect
	})


def home(request):
	if request.user.is_authenticated:
		libraries = Library.objects.filter(user=request.user)
		return render(request, "base/home.html",{
			'libraries': libraries
		})
	else:	
		return render(request, "base/login.html")

base/templates/base/base.html
{% extends 'base/template.html' %}

{% block navigation_wrapper %}
	{% with navigation=True %}
		{{ block.super }}
	{% endwith%}
{% endblock %}

{% block base %}
<div id="content" class="base">
	<main>
		{% block content %}{% endblock %}
	</main>
</div>
<div id="footer">
	{% include "base/footer.html" %}
</div>
{% endblock %}

base/templates/base/base_full.html
{% extends 'base/template.html' %}

{% block base %}
<div id="content" class="base-full">
	<main>
		{% block content %}{% endblock %}
	</main>
</div>
{% endblock %}

base/templates/base/footer.html
<footer class="py-4 bg-light mt-auto">
	<div class="container-fluid">
		<div class="d-flex align-items-center justify-content-between small">
			<div class="text-muted">Copyright &copy; birkoss.com 2020</div>
			<div><a href="#">Privacy Policy</a> &middot; <a href="#">Terms &amp; Conditions</a></div>
		</div>
	</div>
</footer>

base/templates/base/home.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container">

	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
		<h1 class="h2">Bibliothèque</h1>
		<a href="{% url 'library/add' %}" class="btn btn-primary btn-sm">Créer</a>
	</div>

	{% if libraries %}
		<table class="table table-striped">
			<thead>
				<tr>
					<th scope="col">Nom</th>
					<th scope="col">Status</th>
					<th scope="col">Catégories</th>
					<th scope="col">Actions</th>
				</tr>
			</thead>
			<tbody>
				{% for library in libraries %}
				<tr>
					<td>{{ library.name }}</td>
					<td>{% if library.active %}<span class="badge badge-success">publiée</span>{% else %}<span class="badge badge-warning">non-publiée</span>{% endif %}</td>
					<td><a href="{% url 'library-category/archive' library.id %}">{{ library.librarycategory_set.all.count }} catégorie(s)</a></td>
					<td>
						<a href="{% url 'library/edit' library.id %}">Modifier</a> &nbsp;-&nbsp;
						<a href="{% url 'library/single' library.slug %}" target="_blank">Voir</a> &nbsp;-&nbsp;
						<a href="{% url 'library/single' library.slug %}" target="_blank">Publier</a>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	{% else %}
		<div class="alert alert-warning" role="alert">
			Vous n'avez aucune bibiothèque. Créer une <a href="{% url 'library/add' %}">nouvelle bibliothèque</a>.
		</div>
	{% endif %}

</div>

{% endblock %}

base/templates/base/login.html
{% extends 'base/base_full.html' %}

{% load static %}

{% block content %}

<img class="mb-4" src="{% static 'base/medias/logo.png' %}" alt="" width="100" height="100">

<h1 class="h4 mb-3 font-weight-normal">Se connecter avec</h1>

<a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-lg btn-google btn-block text-uppercase" type="submit"><i class="fab fa-google mr-2"></i> Google</a>

<a href="{% url 'social:begin' 'facebook' %}" class="btn btn-lg btn-facebook btn-block text-uppercase" type="submit"><i class="fab fa-facebook-f mr-2"></i> Facebook</a>

<p class="mt-5 mb-3 text-muted">&copy; 2020</p>

{% endblock %}

base/templates/base/profile.html
{% extends 'base/base.html' %}

{% block page_title %}Profile{% endblock %}

{% block content %}
<div class="container">
	<div class="row justify-content-center">
		<div class="col-lg-5">
			<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
				<h1 class="h2">Profile</h1>
			</div>
			
			<div class="card shadow-lg border-0 rounded-lg">
				<div class="card-body">
					<h3 class="small mb-3 text-muted social-media">Google</h3>
					{% if google_login %}
						<p>Connected as <strong>{{ google_login }}</strong></p>
						{% if can_disconnect %}
							<form method="post" action="{% url 'social:disconnect' 'google-oauth2' %}">
								{% csrf_token %}
								<button class="btn btn-primary" type="submit">Disconnect from Google</button>
							</form>
						{% endif %}
					{% else %}
						<a class="btn btn-primary" href="{% url 'social:begin' 'google-oauth2' %}">Connect to Google</a>
					{% endif %}

					<h3 class="small mb-3 text-muted social-media">Facebook</h3>
					{% if facebook_login %}
						<p>Connected</p>
						{% if can_disconnect %}
							<form method="post" action="{% url 'social:disconnect' 'facebook' %}">
								{% csrf_token %}
								<button class="btn btn-primary" type="submit">Disconnect from Facebook</button>
							</form>
						{% endif %}
					{% else %}
						<a class="btn btn-primary" href="{% url 'social:begin' 'facebook' %}">Connect to Facebook</a>
					{% endif %}

				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

base/templates/base/template.html
{% load static %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
		<meta name="description" content="" />
		<title>{% block page_title %}Books{% endblock %}</title>
		<link rel="icon" href="{% static 'base/favicon.ico' %}" />

		{% compress css %}
			<link href="{% static 'base/css/bootstrap.css' %}" rel="stylesheet" />
			<link href="{% static 'base/css/app.css' %}" rel="stylesheet" async />
		{% endcompress %}
	</head>

	<body class="page{% if request.resolver_match.url_name %} {{ request.resolver_match.url_name }}{% endif %}{% if user.is_authenticated %} logged-in{% endif %}">
		{% block navigation_wrapper %}
			{% if navigation %}
				<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
					<a class="navbar-brand" href="{% url 'library/archive' %}">Books</a>

					{% block sidebar_wrapper %}
						{% if sidebar %}
							<button class="btn btn-link btn-sm order-0 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
						{% endif %}
					{% endblock %}

					<!-- Navbar-->
					<ul id="main-nav" class="navbar-nav ml-auto">
						<li class="nav-item"><a class="nav-link" href="{% url 'library/archive' %}">Bibliothèques</a></li>
						{% if user.is_authenticated %}
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" id="user-dropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-edit fa-fw"></i></a>
							<div class="dropdown-menu dropdown-menu-right" aria-labelledby="user-dropdown">
								<a class="dropdown-item" href="#">Create Product</a>
								<a class="dropdown-item" href="#">Manage Products</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
							</div>
						</li>
						{% endif %}
					</ul>
				</nav>
			{% endif %}
		{% endblock %}

		{% block base %}{% endblock %}

		{% if user.is_authenticated %}
			<script type="text/javascript">
				var AJAX_CSRF_TOKEN = "{{ csrf_token }}";
			</script>
		{% endif %}

		{% compress js %}
			<script src="{% static 'base/js/jquery.js' %}"></script>
			<script src="{% static 'base/js/jquery-ui.min.js' %}"></script>
			<script src="{% static 'base/js/bootstrap.js' %}"></script>
			<script src="{% static 'base/js/font-awesome.js' %}"></script>
			<script src="{% static 'base/js/app.js' %}"></script>
		{% endcompress %}
	</body>
</html>